"""empty message

Revision ID: a3a587caf2ce
Revises: bc4e53bfbfdf
Create Date: 2020-07-30 17:58:51.571054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a587caf2ce'
down_revision = 'bc4e53bfbfdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('latitude', sa.String(length=70), nullable=False))
    op.add_column('hotels', sa.Column('longitude', sa.String(length=70), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'longitude')
    op.drop_column('hotels', 'latitude')
    # ### end Alembic commands ###
