"""empty message

Revision ID: cc3b0f0860d5
Revises: 5871655bb18f
Create Date: 2020-07-23 18:41:02.015852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc3b0f0860d5'
down_revision = '5871655bb18f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('home_truths', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('policy', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('policy', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('home_truths', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
