export const FETCH_REG_REQUEST = "FETCH_REG_REQUEST";
export const FETCH_REG_FAILURE = "FETCH_REG_FAILURE";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST"
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS"
export const GOOGLE_LOGIN_FAILURE = "GOOGLE_LOGIN_FAILURE"

export const LOGOUT = "LOGOUT"