/*
export const FETCH_HOTEL_DATA = "FETCH_HOTEL_DATA";
export const FETCH_HOTEL_DATA_FAILURE = "FETCH_HOTEL_DATA__FAILURE";
export const FETCH_HOTEL_DATA__SUCCESS = "FETCH_HOTEL_DATA__SUCCESS";
*/
export const FETCH_LIST_REQUEST = "FETCH_LIST_REQUEST"
export const FETCH_LIST_FAILURE = "FETCH_LIST_FAILURE"
export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS"

export const FETCH_BOOKING_DATES = "FETCH_BOOKING_DATES"