from ..models.EntityModel import EntityModel
from app.main import db
import jwt
import datetime
from app.main.settings import key
from ..utils.save_data import save_changes
import json
import razorpay

client = razorpay.Client(auth = ("rzp_test_MqHwbPLOYmrkkI", "VGcpAjSN1901I9v8uTTIOx0i"))
client.set_app_details({"title" : "onefinestay", "version" : "1.0"})
#Function for adding to catalog data
def create_order(data):

    #hotel_images_json = json.dumps(data["hotel_images"])
    #features_json = json.dumps(data["features"])

    order_amount = data["order_amount"]
    order_currency = 'INR'
    order_receipt = data["order_receipt"]
    notes = {'Message': 'Demo'}    
    
    order_id = client.order.create(dict(amount=order_amount, currency=order_currency, receipt=order_receipt, notes=notes, payment_capture='1'))

    

    print(order_id["id"]," is the order_id generated by Razorpay")
    
    if order_id:
        return True, {"order_id" : order_id["id"], "order_currency" : order_currency, "order_amount" : order_amount}
    else:
        return False, {}


    """
    new_asset = EntityModel(name = data["name"],
                hotel_images = data["hotel_images"],
                city = data["city"],
                address = data["address"],
                capacity = data["capacity"],
                bedrooms = data["bedrooms"],
                bathrooms = data["bathrooms"],
                cost_per_night = data["cost_per_night"],
                description = data["description"],
                features = data["features"],
                home_truth_id = data["home_truth_id"],
                policy_id =  data["policy_id"],
                )
    


    save_changes(new_asset)
    user_id = new_asset.id
    """
