from ..models.EntityModel import EntityModel
from app.main import db
import jwt
import datetime
from app.main.settings import key
from ..utils.save_data import save_changes
import json
import razorpay

client = razorpay.Client(auth = ("rzp_test_MqHwbPLOYmrkkI", "VGcpAjSN1901I9v8uTTIOx0i"))
client.set_app_details({"title" : "onefinestay", "version" : "1.0"})
#Function for adding to catalog data
def validate_payment(data):

    #hotel_images_json = json.dumps(data["hotel_images"])
    #features_json = json.dumps(data["features"])

    razorpay_payment_id = data["razorpay_payment_id"]
    razorpay_order_id = data["razorpay_order_id"]
    razorpay_signature = data["razorpay_signature"]   
    
    client = razorpay.Client(auth = ("<YOUR_KEY_ID>", "<YOUR_KEY_SECRET>"))
    params_dict = { 
    'razorpay_order_id': razorpay_payment_id, 
    'razorpay_payment_id': razorpay_order_id,
    'razorpay_signature': razorpay_signature
    }

    valid = client.utility.verify_payment_signature(params_dict)


    print(valid," is the valid generated by Razorpay Signature Validation")
    
    if valid:
        return True
    else:
        return False
